"""add_task_completion_fields

Revision ID: 670611da4947
Revises: 
Create Date: 2026-04-17 14:49:14.780540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670611da4947'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completion_note', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('completion_submitted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'completion_submitted_at')
    op.drop_column('tasks', 'completion_note')
    # ### end Alembic commands ###
